### ISSUE TITLE
Control server action pending status via `indicator` in server/web components

### ISSUE THREAD

**Issue by aralroca** [brisa-build/brisa#88]
Related to https://github.com/aralroca/brisa/issues/87

Add extended HTML attribute `indicator` (inspired by [HTMX indicator](https://htmx.org/attributes/hx-indicator/), but different behavior):

### In server/web components (both):

```tsx
const incrementing = indicate('increment')
const decrementing = indicate('decrement')

return (
    <>
      <button
        idicator={[incrementing, decrementing]}
        indicateClick={incrementing}
        onClick={increment}
      >
        Increment <span indicator={incrementing} class="spinner" />
      </button>
      <button
        idicator={[incrementing, decrementing]}
        indicateClick={decrementing}
        onClick={decrement}
      >
        Decrement <span indicator={decrementing} class="spinner" />
      </button>
    </>
  );
```

The `brisa-request` class is added to the elements with the `indicator` of the current server action meanwhile this action is pending.

Example of CSS used for this example:

```css
button.brisa-request {
  pointer-events: none;
  cursor: not-allowed;
  background-color: rgba(0,0,0,0.1);
}
.spinner, .btn-text.brisa-request {
  display: none;
}
.spinner.brisa-request {
  display: inline;
}
```

New attributes:

- `indicateClick` - IndicatorSignal - It's the way to register the action to the indicator
- `indicator` - Adds a class `brisa-request` to the element only during action request time. This allows things like transitions, disable buttons in request time, display spinner...

### Only in web components

In web components the `indicator` could also be used as a signal:

```tsx
Increment {incrementing.value && <span class="spinner" />}
```
